export const GET_AUTH_STATE = "GET_AUTH_STATE";
export const CONVERT_GOOGLE_TOKEN_SUCCESS = "CONVERT_GOOGLE_TOKEN_SUCCESS";
export const HANDLE_GOOGLE_LOGOUT = "HANDLE_GOOGLE_LOGOUT";

export const FETCH_SECRETS = "FETCH_SECRETS";

export const TOKEN_REFRESHING = "TOKEN_REFRESHING";
export const TOKEN_REFRESHED = "TOKEN_REFRESHED";
